### ISSUE TITLE
Optitype crashes with python2.7.17 due to configparser

### ISSUE THREAD

**Issue by naumenko-sa** [FRED-2/OptiType#101]
Hello OptiType developers!

Thanks for developing and supporting OptiType!

In a fresh 1.2.0 bcbio installation variant calling with `hlacaller: optitype` fails at

https://github.com/FRED-2/OptiType/blob/master/OptiTypePipeline.py#L231

A fresh one has python 2.7.17 in python2 environment and a backported module configparser:
```
>>> import os
>>> import configparser
>>> config = configparser.SafeConfigParser(os.environ)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1264, in __init__
    super(SafeConfigParser, self).__init__(*args, **kwargs)
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 637, in __init__
    self._read_defaults(defaults)
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1255, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/path/bcbio120/anaconda/envs/python2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 750, in read_dict
    raise DuplicateOptionError(section, key, source)
backports.configparser.DuplicateOptionError: While reading from u'<dict>': option u'http_proxy' in section u'DEFAULT' already exists
```

A less fresh one with python 2.7.15 does not have it and works fine:
```
>>> import os
>>> import configparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named configparser
>>> import ConfigParser as configparser
>>> config = configparser.SafeConfigParser(os.environ)
```

Andras @andras86, would it be possible to fix this on the Optitype side?

Sergey

**Comment by koujiaodahan** [comment]
my conda  python:  2.7.16 ;has similar errors~~~~~~~~~~~~~~~~~~``` 
Log : 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0   697      0   421k --:--:-- --:--:-- --:--:--  421k^M888   191  191   191    0   697   8983  32781 --:--:-- --:--:-- --:--:--     0
[M::bam2fq_mainloop] processed 645126 reads
[M::bam2fq_mainloop] processed 208 reads
[M::bam2fq_mainloop] processed 206 reads
Traceback (most recent call last):
  File "OptiType-master/OptiTypePipeline.py", line 231, in <module>
    config = configparser.SafeConfigParser(os.environ)
  File "anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1332, in __init__
    super(SafeConfigParser, self).__init__(*args, **kwargs)
  File "anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 710, in __init__
    self._read_defaults(defaults)
  File "anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1323, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File /anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 823, in read_dict
    raise DuplicateOptionError(section, key, source)
backports.configparser.DuplicateOptionError: While reading from u'<dict>': option u'runlevel' in section u'DEFAULT' already exists

**Comment by koujiaodahan** [comment]
I try to use in 2.7.15,but errors as follows :
$sh test15_run_optitye_xin2.sh
Traceback (most recent call last):
  File "/OptiTypePipeline.py", line 129, in <module>
    from model import OptiType
  File "/share/optitype-1.3.2-3/model.py", line 19, in <module>
    from pyomo.environ import ConcreteModel, Set, Param, Var, Binary, Objective, Constraint, ConstraintList, maximize
  File "/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 13, in <module>
    import pyomo.core
  File "/python2.7/site-packages/pyomo/core/__init__.py", line 10, in <module>
    from pyomo.util.plugin import PluginGlobals
  File "lib/python2.7/site-packages/pyomo/util/__init__.py", line 10, in <module>
    from pyomo.util._task import pyomo_api, PyomoAPIData, PyomoAPIFactory
  File "/lib/python2.7/site-packages/pyomo/util/_task.py", line 22, in <module>
    from pyomo.util import plugin
  File "test_python7.15/lib/python2.7/site-packages/Pyomo-5.6.10.dev0-py2.7-linux-x86_64.egg/pyomo/__init__.py", line 11, in <module>
    from . import common
  File "/lib/python2.7/site-packages/Pyomo-5.6.10.dev0-py2.7-linux-x86_64.egg/pyomo/common/__init__.py", line 13, in <module>
    from . import log
ImportError: cannot import name log
