### ISSUE TITLE
Error with solver

### ISSUE THREAD

**Issue by warrenlr** [FRED-2/OptiType#111]
Hello,

kind of stuck, I installed optitype with conda. Had to use python v2.7 (miniconda2) in order to install it.

When I run this command:
```
.../miniconda2/bin/OptiTypePipeline.py -i sample_1_fished.fastq sample_2_fished.fastq --rna -v -o optitypeOUT
```

I get this error:

```
...
Memory used: 0.2 Mb (159157 bytes)
Writing MIP solution to '/var/tmp/tmpfRSZit.glpk.raw'...
148 lines were written
invalid literal for int() with base 10: 'c'
Traceback (most recent call last):
  File "/projects/rwarren_prj2/bin/miniconda2/bin/OptiTypePipeline.py", line 421, in <module>
    result = op.solve(args.enumerate)
  File "/projects/rwarren_prj2/bin/miniconda2/share/optitype-1.3.2-3/model.py", line 153, in solve
    res = self.__solver.solve(self.__instance, options={}, tee=self.__verbosity)
  File "/projects/rwarren_prj2/bin/miniconda2/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 487, in solve
    result = self._postsolve()
  File "/projects/rwarren_prj2/bin/miniconda2/lib/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 161, in _postsolve
    results = self.process_output(self._rc)
  File "/projects/rwarren_prj2/bin/miniconda2/lib/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 220, in process_output
    self.process_soln_file(results)
  File "/projects/rwarren_prj2/bin/miniconda2/lib/python2.7/site-packages/pyomo/solvers/plugins/solvers/GLPK.py", line 445, in process_soln_file
    raise ValueError(msg)
ValueError: Error parsing solution data file, line 1
```

Seems to be linked to an older version of GLPK, but can't confirm.

When I update glpk to the latest version using conda, the correct version gets installed in  /projects/rwarren_prj2/bin/miniconda2/pkgs

but /projects/rwarren_prj2/bin/miniconda2/lib/python2.7/site-packages/pyomo
remains unchanged.

Help appreciated!

**Comment by warrenlr** [comment]
solved with install of a different solver : coincbc
