### ISSUE TITLE
AttributeError: 'Index' object has no attribute 'difference'

### ISSUE THREAD

**Issue by renyuan01** [FRED-2/OptiType#115]
conda create -n optitype python=2.7.3
conda install -n optitype -c bioconda optitype
conda activate optitype
bam=/home/ry/analysis/data/optitype/bam
raw=/home/ry/analysis/data/optitype/raw
fastq=/home/ry/analysis/data/optitype/fastq
hla=/home/ry/analysis/data/optitype/hla
dnaref=/home/ry/analysis/data/optitype/hlareference/hla_reference_dna.fasta
OptiTypePipeline.py -i $fastq/GYH1.fastq $fastq/GYH2.fastq --dna -v -o $hla -p GYH.optitype.dna

mapping with 11 threads...

 0:00:00.36 Mapping GYH1.fastq to GEN reference...

 0:00:32.76 Mapping GYH2.fastq to GEN reference...

 0:01:06.82 Generating binary hit matrix.
0:01:06.83 Loading /home/ry/analysis/data/optitype/hla/2020_09_03_21_50_24_1.bam started. Number of HLA reads loaded (updated every thousand):
1K...2K...3K...4K...5K...6K...7K...8K...9K...10K...11K...
 0:01:09.90 11460 reads loaded. Creating dataframe...
0:01:10.22 Dataframes created. Shape: 11460 x 11179, hits: 2224373 (2224373), sparsity: 1 in 57.59
0:01:11.55 Loading /home/ry/analysis/data/optitype/hla/2020_09_03_21_50_24_2.bam started. Number of HLA reads loaded (updated every thousand):
1K...2K...3K...4K...5K...6K...7K...8K...9K...10K...11K...
 0:01:14.45 11318 reads loaded. Creating dataframe...
0:01:14.77 Dataframes created. Shape: 11318 x 11179, hits: 2149552 (2149552), sparsity: 1 in 58.86

Traceback (most recent call last):
  File "/home/ry/miniconda3/envs/optitype/bin/OptiTypePipeline.py", line 347, in <module>
    binary_p, binary_mis, binary_un =  ht.create_paired_matrix(binary1, binary2)
  File "/home/ry/miniconda3/envs/optitype/share/optitype-1.3.2-1/hlatyper.py", line 518, in create_paired_matrix
    only_1 = binary_1.index.difference(binary_2.index)
AttributeError: 'Index' object has no attribute 'difference'

**Comment by renyuan01** [comment]
conda list
# packages in environment at /home/ry/miniconda3/envs/optitype:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
cairo                     1.12.2                        0    defaults
certifi                   2016.9.26                py27_0    conda-forge
dateutil                  2.4.1                    py27_0    defaults
freetype                  2.4.10                        0    defaults
future                    0.18.2                   py27_0    conda-forge
glpk                      4.57                          0    bioconda
hdf5                      1.8.9                         1    defaults
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgomp                   9.3.0               h24d8f2e_16    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
matplotlib                1.1.1                np17py27_1    defaults
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                 py27_1003    conda-forge
numexpr                   2.2.2                np17py27_1    defaults
numpy                     1.7.1                    py27_2    defaults
openssl                   1.0.1k                        1    defaults
optitype                  1.3.2                    py27_1    bioconda
pandas                    0.13.0               np17py27_0    defaults
pip                       20.0.2                   py27_1    conda-forge
pixman                    0.26.2                        0    defaults
ply                       3.11                       py_1    conda-forge
py2cairo                  1.10.0                   py27_1    defaults
pyomo                     4.1.10527                py27_1    bioconda
pysam                     0.8.4                    py27_0    bioconda
pytables                  3.0.0                np17py27_1    defaults
python                    2.7.3                         7    defaults
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyutilib                  5.1.3556                 py27_0    bioconda
razers3                   3.5.8                hb7ba0dd_0    bioconda
readline                  6.2                           0    conda-forge
samtools                  1.3.1                         0    bioconda
setuptools                36.4.0                   py27_1    defaults
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
system                    5.8                           2    defaults
tk                        8.5.18                        0    defaults
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge

**Comment by bobojin46** [comment]
Hi I ran into this erro,too. Did you solve that problem now? Can you tell me the solution if possible? thank u very much
