### ISSUE TITLE
error using docker

### ISSUE THREAD

**Issue by anoronh4** [FRED-2/OptiType#132]
I am trying your dockers and running into errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/OptiType/OptiTypePipeline.py", line 304, in <module>
    table, features = ht.load_hdf(ALLELE_HDF, False, 'table', 'features')
  File "/usr/local/bin/OptiType/hlatyper.py", line 88, in load_hdf
    to_return = tuple((store[table] for table in args))
  File "/usr/local/bin/OptiType/hlatyper.py", line 88, in <genexpr>
    to_return = tuple((store[table] for table in args))
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 483, in __getitem__
    return self.get(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 671, in get
    return self._read_group(group)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 1349, in _read_group
    return s.read(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 2904, in read
    start=_start, stop=_stop)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 2459, in read_array
    ret = node[0][start:stop]
  File "/usr/local/lib/python2.7/dist-packages/tables/vlarray.py", line 671, in __getitem__
    return self.read(start, stop, step)[0]
  File "/usr/local/lib/python2.7/dist-packages/tables/vlarray.py", line 811, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2106, in tables.hdf5extension.VLArray._read_array (tables/hdf5extension.c:24649)
ValueError: cannot set WRITEABLE flag to True of this array
Closing remaining open files:/usr/local/bin/OptiType/data/alleles.h5...done
```
I am using `fred2/optitype:release-v1.3.1` and `fred2/optitype:latest` and getting the same problem. here is my usage:
```
OptiTypePipeline.py --verbose -i sample.hla.1.fastq sample.hla.2.fastq -e 1 -b .009 \
        -p "SampleA" -c config.ini --dna --outdir SampleA
```
Could you help to solve this issue?

**Comment by malonzm1** [comment]
I got a similar error. I downgraded the numpy version to 1.15.4.
