### ISSUE TITLE
Installation problem with pyomo module

### ISSUE THREAD

**Issue by Elisa89m** [FRED-2/OptiType#139]
Hi, 
I'm trying to install Optitype but I have some problem with pyomo module, when I'm trying to use Optitype it returns this error:

```
Traceback (most recent call last):
  File "/PATH/anaconda3/envs/python2_env/bin/pyomo", line 4, in <module>
    import pyomo.scripting.pyomo_main
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/scripting/__init__.py", line 14, in <module>
    import pyomo.scripting.pyomo_command
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/scripting/pyomo_command.py", line 25, in <module>
    import pyomo.scripting.util
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/scripting/util.py", line 65, in <module>
    from pyomo.opt import ProblemFormat
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/opt/__init__.py", line 14, in <module>
    from pyomo.opt.base import *
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/opt/base/__init__.py", line 14, in <module>
    from pyomo.opt.base.convert import *
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/opt/base/convert.py", line 16, in <module>
    from pyomo.opt.base.formats import guess_format
  File "/PATH/anaconda3/envs/python2_env/lib/python2.7/site-packages/pyomo/opt/base/formats.py", line 16, in <module>
    from pyutilib.enum import Enum
  File "/home/manager/.local/lib/python2.7/site-packages/pyutilib/enum/__init__.py", line 18, in <module>
    package) that supersedes this library.""")
ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.
```

Reading on internet it seems that this problem could be due to the python version but I need to install it under python2.7 as required from Optitype.
Can you help me? Is there a solution for this error?
I tried also to updated pyomo version even if optitype requires an older one. 

Thank you in advance for your time.

Elisa

**Comment by b-schubert** [comment]
you need to specify the exact pyomo version (as in the readme). 
pip install "pyomo==4.2"
