### ISSUE TITLE
Optitype crashes with "IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index"

### ISSUE THREAD

**Issue by holtgrewe** [FRED-2/OptiType#46]
Looking at the commits, this might already be fixed. However, can we get a release so I can update the Bioconda package?

```
+ OptiTypePipeline.py --config /tmp/tmp.7tWxKjFp3A/tmp.giJXfvqJlQ/tmp.d/optitype.ini --verbose --input /tmp/tmp.7tWxKjFp3A/tmp.giJXfvqJlQ/tmp.d/reads_left.fastq /tmp/tmp.7tWxKjFp3A/tmp.giJXfvqJlQ/tmp.d/reads_right.fastq --dna --outdir /tmp/tmp.7tWxKjFp3A/tmp.giJXfvqJlQ/out.tmp
Traceback (most recent call last):
  File "/tmp/tmp.7tWxKjFp3A/tmpl00sjz26/.snakemake/conda/7a1aa8ba/bin/OptiTypePipeline.py", line 427, in <module>
    coverage_mat = ht.calculate_coverage(plot_variables, features, hlatype, features_used)
  File "/tmp/tmp.7tWxKjFp3A/tmpl00sjz26/.snakemake/conda/7a1aa8ba/share/optitype-1.2-0/hlatyper.py", line 626, in calculate_coverage
    coverage[bool(i_mismatches)][i_pairing-1][i_hitcount-1][i_pos-1:i_pos-1+i_read_length] += 1
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
+ rm -rf /tmp/tmp.7tWxKjFp3A/tmp.giJXfvqJlQ
Traceback (most recent call last):
  File "/home/mholtgre/Development/open_pipeline/tools/cubi_wrappers/cubi_wrappers/wrappers/optitype/.snakemake.nq3mkf2a.wrapper.py", line 119, in <module>
    """)
  File "/bioconda/2017-03/miniconda3/lib/python3.4/site-packages/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
```

**Comment by andras86** [comment]
Sure!
