### ISSUE TITLE
[External] GLPK error 4.5x

### ISSUE THREAD

**Issue by b-schubert** [FRED-2/OptiType#56]
With Pyomo 5.x the following error occurs for GLPK <= 4.5x (see https://github.com/Pyomo/pyomo/issues/146)

```Writing MIP solution to `/tmp/tmpDUGZvJ.glpk.raw'...
474 lines were written
ERROR: Expecting 's' row after 'c' rows
Traceback (most recent call last):
  File "OptiTypePipeline.py", line 405, in <module>
    result = op.solve(args.enumerate)
  File "/home/travis/build/FRED-2/OptiType/model.py", line 153, in solve
    res = self.__solver.solve(self.__instance, options={}, tee=self.__verbosity)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 610, in solve
    result = self._postsolve()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 268, in _postsolve
    results = self.process_output(self._rc)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 330, in process_output
    self.process_soln_file(results)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pyomo/solvers/plugins/solvers/GLPK.py", line 362, in process_soln_file
    raise ValueError(msg)
ValueError: Error parsing solution data file, line 2```

**Comment by b-schubert** [comment]
Internally resolved for Travis-CI tests in PR #57
