### ISSUE TITLE
E::hts_open_format] Failed to open file out/2017_11_18_07_05_37/2017_11_18_07_05_37_1.bam

### ISSUE THREAD

**Issue by dhwnai2410** [FRED-2/OptiType#66]
prateek@cpu:~/dhwani$ sudo docker run -v test:/test -t fred2/optitype -i NA11995_SRR766010_1_fished.fastq NA11995_SRR766010_1_fished.fastq -d -o out
sudo: unable to resolve host cpu: Connection timed out
[E::hts_open_format] Failed to open file out/2017_11_18_07_05_37/2017_11_18_07_05_37_1.bam
Traceback (most recent call last):
  File "/usr/local/bin/OptiType/OptiTypePipeline.py", line 299, in <module>
    pos, read_details = ht.pysam_to_hdf(bam_paths[0])
  File "/usr/local/bin/OptiType/hlatyper.py", line 186, in pysam_to_hdf
    sam = pysam.AlignmentFile(samfile, sam_or_bam)
  File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 621, in pysam.libcalignmentfile.AlignmentFile._open
IOError: [Errno 2] could not open alignment file `out/2017_11_18_07_05_37/2017_11_18_07_05_37_1.bam`: No such file or directory

**Comment by b-schubert** [comment]
you have to write to the same folder that you mounted from your host system (i.e. -o /test)

See:

```
docker run -v /path/to/data/folder:/data/ -t fred2/optitype -i input1 [input2] (-r|-d) -o /data/
```
