### ISSUE TITLE
permission error occured when using docker file

### ISSUE THREAD

**Issue by zd200572** [FRED-2/OptiType#69]
when using docker file, It give me an error info, it seems to be the permission error of mkdir function. I googled and used the solution of add '--previliged=true', but it still doesn't work. My system is Ubuntu 16.04.3 and docker ce. Is there anything I can do to solve it?

Traceback (most recent call last):
  File "/usr/local/bin/OptiType/OptiTypePipeline.py", line 264, in <module>
    os.makedirs(out_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/data/2017_12_31_08_56_44'

another error info I encounter is the software installation by bioconda, the error info is ：

0:12:16.95 Generating binary hit matrix.
Traceback (most recent call last):
  File "/home/zjd/miniconda3/envs/python2.7/bin/OptiTypePipeline.py", line 303, in <module>
    pos, read_details = ht.pysam_to_hdf(bam_paths[0])
  File "/home/zjd/miniconda3/envs/python2.7/share/optitype-1.2.1-0/hlatyper.py", line 186, in pysam_to_hdf
    sam = pysam.AlignmentFile(samfile, sam_or_bam)
AttributeError: 'module' object has no attribute 'AlignmentFile'

**Comment by b-schubert** [comment]
how did you call the docker container? Did you mount a directory of your host system to /data ?

**Comment by AAlhendi1707** [comment]
same issue here
