### ISSUE TITLE
Getting a non in index error

### ISSUE THREAD

**Issue by kippakers** [FRED-2/OptiType#7]
Hello,
Optitype keeps giving me the same error for a group of samples.  This is single end, 100bp data.  Normally the software works great for me so I don't think it's my version/setup.  I can send you ~1Mb fastq file to recreate if you like.  
Command
```
python OptiTypePipeline.py -i ${path}/temp2_fished1.fastq --rna --o ${path} -v
```
Error:

```python
Problem data seem to be well scaled
Constructing initial basis...
Size of triangular part = 408
Solving LP relaxation...
GLPK Simplex Optimizer, v4.49
408 rows, 248 columns, 2006 non-zeros
      0: obj =   0.000000000e+00  infeas =  1.000e+00 (0)
*     1: obj =   0.000000000e+00  infeas =  0.000e+00 (0)
*   192: obj =   3.090929000e+03  infeas =  0.000e+00 (0)
OPTIMAL SOLUTION FOUND
Integer optimization begins...
+   192: mip =     not found yet <=              +inf        (1; 0)
+   192: >>>>>   3.090929000e+03 <=   3.090929000e+03   0.0% (1; 0)
+   192: mip =   3.090929000e+03 <=     tree is empty   0.0% (0; 1)
INTEGER OPTIMAL SOLUTION FOUND
Time used:   0.0 secs
Memory used: 0.7 Mb (727283 bytes)
Writing MIP solution to `/tmp/tmpGkiOZD.glpk.raw'...
672 lines were written

0:14:51.33 Result dataframe has been constructed...
Traceback (most recent call last):
  File "OptiTypePipeline.py", line 315, in <module>
    r = result_4digit[["A1", "A2", "B1", "B2", "C1", "C2", "nof_reads", "obj"]]
  File "~/common/python/2.7.6/lib/python2.7/site-packages/pandas/core/frame.py", line 1781, in __getitem__
    return self._getitem_array(key)
  File "~/common/python/2.7.6/lib/python2.7/site-packages/pandas/core/frame.py", line 1825, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "~/common/python/2.7.6/lib/python2.7/site-packages/pandas/core/indexing.py", line 1140, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['B1' 'B2'] not in index"
```

**Comment by andras86** [comment]
Hi Kipp,

Just send me the fastq file and I'll have a look at it. Seems like the 
kind of problem when there are no reads mapping to a locus at all (HLA-B 
in this case), but I'll check it out tomorrow.

Cheers,
Andras
