### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by raerose013** [FRED-2/OptiType#8]
Hi,

I've been running OptiType mostly successfully; however, sometimes there is a KeyError that is raised, which causes the program to stop.  It only affects some samples but I haven't found a common link between them.  I've included the error message and was wondering if you had encountered this before.

Traceback (most recent call last):
  File "[base]/OptiType/OptiTypePipeline.py", line 315, in <module>
    r = result_4digit[["A1", "A2", "B1", "B2", "C1", "C2", "nof_reads", "obj"]]
  File "[base]/python/lib/python2.7/site-packages/pandas/core/frame.py", line 1672, in \__getitem_\_
    return self._getitem_array(key)
  File "[base]/python/lib/python2.7/site-packages/pandas/core/frame.py", line 1716, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "[base]/python/lib/python2.7/site-packages/pandas/core/indexing.py", line 1085, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['A1' 'A2'] not in index"

Thanks

**Comment by b-schubert** [comment]
This happens when no read maps to a specific HLA loci. In the upcoming updates we will raise a flag if this happens.

**Comment by andras86** [comment]
It's actually been fixed since, we just forgot to close the issue.
