### ISSUE TITLE
hi everyone, did any of you overcome thay type of issue ?

### ISSUE THREAD

**Issue by AmyNjaaye** [FRED-2/OptiType#80]
```0:00:00.63 Mapping test.fastq to NUC reference...
Failed to open genome file /usr/bin/data/hla_reference_rna.fasta
Exiting ...
Traceback (most recent call last):
 File "/usr/bin/optitype", line 303, in <module>
 table, features = ht.load_hdf(ALLELE_HDF, False, 'table', 'features')
  File "/usr/bin/hlatyper.py", line 83, in load_hdf
    store = pd.HDFStore(in_hdf, 'r')
  File "/usr/lib/python2.7/dist-packages/pandas/io/pytables.py", line 448, in __init__
    self.open(mode=mode, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pandas/io/pytables.py", line 587, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tables/file.py", line 783, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 369, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:4577)
  File "/usr/lib/python2.7/dist-packages/tables/utils.py", line 156, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
IOError: ``/usr/bin/data/alleles.h5`` does not exist```

My command line was: 

python2.7 /usr/bin/optitype -i /output/test.fastq --rna -c /data/Logiciels_metiers/OptiType-master/config.ini.example --outdir /output/ --verbose

**Comment by hfl112** [comment]
I downgraded numpy and it worked:
`pip install numpy==1.15.4
`
